name: StyleCheck

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  clang-format:
    runs-on: ubuntu-latest

    env:
      LLVM_VERSION: 17

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ env.LLVM_VERSION }}
          rm -rf llvm.sh
          sudo apt install clang-format-${{ env.LLVM_VERSION }}

      - name: Run clang-format
        run: clang-format-${{ env.LLVM_VERSION }} -i $(find -iname "*.[hc]pp" -o -iname "*.[hc]" -type f)

      - name: Report result
        run: |
          if [ -z "$(git status -s)" ]; then
            echo Everything seems to be in order
          else
            echo Formatting problems found!
            git diff --color=always --minimal
            exit 1
          fi

  cmake-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install
        run: pip install cmakelang pyyaml

      - name: Run cmake-format
        run: cmake-format -i $(find -iregex "./.*\.cmake" -or -iregex "./.*\CMakeLists\.txt")

      - name: Report result
        run: |
          if [ -z "$(git status -s)" ]; then
            echo Everything seems to be in order
          else
            echo Formatting problems found!
            git diff --color=always --minimal
            exit 1
          fi

  spacing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: sudo apt-get install moreutils

      - name: Fix spacing
        run: |
          # Fix mixed tabs and spaces
          find . -iregex '.*\.\(c\|h\|hpp\|cpp\|yaml\|yml\|md\|txt\|cmake\|sh\)' -type f -exec bash -c 'expand -t 4 "$0" | sponge "$0"' {} \;

          # Fix trailing white spaces
          find . -iregex '.*\.\(c\|h\|hpp\|cpp\|yaml\|yml\|md\|txt\|cmake\|sh\)' -type f -exec bash -c 'sed -i '' -e's/[[:space:]]*$//' "$0"' {} \;

          # Ensure files end with a new line
          find . -iregex '.*\.\(c\|h\|hpp\|cpp\|yaml\|yml\|md\|txt\|cmake\|sh\)' -type f -exec bash -c 'tail -c1 < "$0" | read -r _ || echo >> "$0"' {} \;

      - name: Report result
        run: |
          if [ -z "$(git status -s)" ]; then
            echo Everything seems to be in order
          else
            echo Formatting problems found!
            git diff --color=always --minimal
            exit 1
          fi

  encoding:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: sudo apt-get install dos2unix recode

      - name: Fix encoding
        run: |
          # Ensure that files are UTF-8 formatted
          find . -iregex '.*\.\(c\|h\|hpp\|cpp\|yaml\|yml\|md\|txt\|cmake\|sh\)' -type f -exec bash -c 'recode UTF-8 "$0" 2> /dev/null' {} \;
          # Ensure that files have LF line endings and do not contain a BOM.
          find . -iregex '.*\.\(c\|h\|hpp\|cpp\|yaml\|yml\|md\|txt\|cmake\|sh\)' -type f -exec bash -c 'dos2unix "$0" 2> /dev/null' {} \;

      - name: Report result
        run: |
          if [ -z "$(git status -s)" ]; then
            echo Everything seems to be in order
          else
            echo Encoding problems found!
            git diff --color=always --minimal
            exit 1
          fi
