name: Windows

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

# Default windows to use bash
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  msvc:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os:
          - "windows-2019"
          - "windows-2022"

        arch:
          - "x86"
          - "x64"

        build_type:
          - "Debug"
          - "Release"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.12.1
        with:
          arch: ${{ matrix.arch }}

      - name: Configure build directory
        run: cmake -B ./build -S ./ -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }}

      - name: Build
        working-directory: ./build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: ./build
        run: ctest . -C ${{ matrix.build_type }}

  clang:
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        build_type:
          - "Debug"
          - "Release"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compiler
        shell: powershell
        run: |
          # Install scoop
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          # Required since CI runner is admin
          # See https://github.com/ScoopInstaller/Install#for-admin
          .\install.ps1 -RunAsAdmin

          scoop install ninja llvm --global

          echo "CXX=clang++" >> $GITHUB_ENV
          echo "C:\ProgramData\scoop\apps\llvm\current\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\scoop\apps\ninja\current"    | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure build directory
        run: cmake -B ./build -S ./ -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }}

      - name: Build
        working-directory: ./build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: ./build
        run: ctest . -C ${{ matrix.build_type }}

  gcc:
    runs-on: windows-2022

    strategy:
      fail-fast: false

      matrix:
        build_type:
          - "Debug"
          - "Release"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install compiler
        shell: powershell
        run: |
          # Install scoop
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          # Required since CI runner is admin
          # See https://github.com/ScoopInstaller/Install#for-admin
          .\install.ps1 -RunAsAdmin

          scoop install ninja gcc --global

          echo "CXX=g++" >> $GITHUB_ENV
          echo "C:\ProgramData\scoop\apps\gcc\current\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\scoop\apps\ninja\current"   | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure build directory
        run: cmake -B ./build -S ./ -DCMAKE_BUILD_TYPE:STRING=${{ matrix.build_type }}

      - name: Build
        working-directory: ./build
        run: cmake --build . --config ${{ matrix.build_type }}

      - name: Run tests
        working-directory: ./build
        run: ctest . -C ${{ matrix.build_type }}
